-- Gold table for total passengers dropped by each vendor
create or refresh materialized view gold_nyctaxi.vendor_passenger_count_gold 
as
select VendorID,
sum(passenger_count) as Total_Passengers_Dropped
from silver_nyctaxi.newyork_taxi_silver
group by VendorID
order by Total_Passengers_Dropped desc;

-- Gold Table revenue generated by each vendor
create or refresh materialized view gold_nyctaxi.vendor_revenue_gold 
as
select VendorID,
round(sum(total_amount),2) as Total_Amount_Earned
from silver_nyctaxi.newyork_taxi_silver
group by VendorID
order by Total_Amount_Earned desc;

-- Gold Table revenue generated by taxitype yellow/green
create or refresh materialized view gold_nyctaxi.taxi_type_gold 
as
select taxitype,
round(sum(total_amount),2) as Revenue_Generated
from silver_nyctaxi.newyork_taxi_silver
group by taxitype
order by Revenue_Generated desc;

--Gold table revenue generated at each date 
create or refresh materialized view gold_nyctaxi.revenue_by_date_gold
as
select date(pickup_datetime) as TheDate,
round(sum(total_amount),2) as RevenueGeneratedPerDay
from silver_nyctaxi.newyork_taxi_silver
group by TheDate
order by RevenueGeneratedPerDay desc;

--Gold Table for vendors who travelled the most tripdistance
create or refresh materialized view gold_nyctaxi.most_travelled_vendor_gold
as
select VendorId,
round(sum(trip_distance),2) as Total_distance_travelled
from silver_nyctaxi.newyork_taxi_silver
group by VendorId
order by Total_distance_travelled desc;

-- Gold Table for passengers based on RateCode
create or refresh materialized view gold_nyctaxi.ratecode_passenger_gold
as
select RateCodeID,
RateCode,
sum(passenger_count) as TotalPassengers
from silver_nyctaxi.newyork_taxi_silver
group by RateCodeID,RateCode
order by TotalPassengers desc;

--Gold Table for most used PaymentType
create or refresh materialized view gold_nyctaxi.mostused_paymenttype_gold
as 
select PaymentTypeID,
PaymentType,
sum(passenger_count) as PaymentTypeByPassenger
from silver_nyctaxi.newyork_taxi_silver
group by PaymentTypeID,PaymentType
order by PaymentTypeByPassenger desc;

--Gold Table for most visited places 
create or refresh materialized view gold_nyctaxi.most_visited_places_gold
as
select LocationID,
Borough,
count(*) as TotalVisits
from silver_nyctaxi.newyork_taxi_silver
group by LocationID,Borough
order by TotalVisits desc;